.\" Manpage for barkeeper.
.\" Contact info@madcow.dev to correct errors or typos.
.TH man 8 "05 Dec 2020" "1.0" "barkeeper man page"
.SH NAME
barkeeper \- barcode database
.SH SYNOPSIS
barkeeper [--verbose]
.SH DESCRIPTION
barkeeper is a barcode database with both Telnet and HTTP/S interface. It displays real-time updates from connected scanners in the web browser.
.SH OPTIONS
There are currently no options defined.
.SH BUGS
No known bugs.
.SH AUTHOR
Leon Krieg <info@madcow.dev>
