.\" Manpage for barkeeper. Run 'make install-docs' to install.
.\" Contact info@madcow.dev to correct any errors or typos.

.TH BARKEEPER 8

.SH NAME
barkeeper \- barcode database

.SH SYNOPSIS
.B barkeeper
.B [ -d | -k | -r | -v | -h ] [ -f
.I filename
.B ] [ -p
.I port
.B ]

.SH DESCRIPTION
barcode database with both Telnet and HTTP/S interface.
It displays real-time updates from connected scanners
in the web browser.

.SH OPTIONS
.IP "-d, --daemon"
Run in daemon mode
.IP "-k, --kill"
Stop active daemon
.IP "-r, --restart"
Restart active daemon. Sorthand for running barkeeper
--kill followed by barkeeper --daemon.
.IP "-f, --file \fIfilename\fR"
Load additional barcode data from CSV file. Can be done
while the daemon is running in the background.
.IP "-p, --port \fIport\fR"
Set telnet port. This option has priority over settings
found in /etc/barkeeper.cfg.
.IP "-v, --verbose"
Output verbose log messages
.IP "-h, --help"
Print help text
.SH FILES

.I /etc/barkeeper.cfg
.RS
System wide configuration file. See README for details.
.RE

.I /var/log/barkeeper.log
.RS
Console output generated while running in daemon mode.
.RE

.I /var/lib/barkeeper/
.RS
Variable state information like the local database.
.RE

.SH BUGS
No known bugs.

.SH AUTHOR
Leon Krieg <\fIinfo@madcow.dev\fR>
